name: Realse to prod

on: 
  release:
    types: [released]

env:
  CACHE_PREFIX_NODE_MODULES: yarn_1.2
  CACHE_PREFIX_NEXT: next_1.1

jobs:
  build_job_for_prod:
    uses: mikero8/kicker/.github/workflows/build.yml@main
    with:
      branch_name: main

  echo_variable:
    steps:
      - name: Echo deployment variables
        id: echo_deploy_vars
        run: |
          echo ${{ needs.build_job.outputs.build_env }}
          echo ${{ needs.build_job.outputs.target_bucket }}

  deploy_to_prod:
    uses: mikero8/kicker/.github/workflows/deploy.yml@main
    with:
      build_env: ${{ needs.build_job_for_prod.outputs.build_env }}
      target_bucket:  ${{ needs.build_job_for_prod.outputs.target_bucket }}
