name: Realse to prod

on: 
  release:
    types: [released]

env:
  CACHE_PREFIX_NODE_MODULES: yarn_1.2
  CACHE_PREFIX_NEXT: next_1.1

jobs:
  build_job_for_prod:
    uses: mikero8/kicker/.github/workflows/build.yml@main
    with:
      branch_name: main

  deploy_for_prod:
    uses: mikero8/kicker/.github/workflows/deploy.yml@main
    with:
      branch_env: ${{ needs.build_job.outputs.branch_env }}
      target_bucket:  ${{ needs.build_job.outputs.target_bucket }}
