name: Realse

on: 
  release:
    types: [prereleased]

env:
  CACHE_PREFIX_NODE_MODULES: yarn_1.2
  CACHE_PREFIX_NEXT: next_1.1

jobs:

  build_job:
    uses: mikero8/kicker/.github/workflows/build.yml@main
    with:
      branch_name: main

  deploy:
    uses: mikero8/kicker/.github/workflows/deploy.yml@main
    with:
      branch_env: ${{ needs.build_job.outputs.branch_env }}
      target_bucket:  ${{ needs.build_job.outputs.target_bucket }}
  # build:
  #   name: Deploy to QA
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - uses: actions/checkout@v1
  #     - name: "call action"
  #       id: last_release
  #       uses: InsonusK/get-latest-release@v1.0.1
  #       with:
  #         myToken: ${{ github.GITHUB_TOKEN }}
  #         exclude_types: "draft"
  #         view_top: 1
  #     - name: "Print result"
  #       run: |
  #         echo "id: ${{ steps.last_release.outputs.id }}"
  #         echo "name: ${{ steps.last_release.outputs.name }}"
  #         echo "tag_name: ${{ steps.last_release.outputs.tag_name }}"
  #         echo "created_at: ${{ steps.last_release.outputs.created_atd }}"
  #         echo "draft: ${{ steps.last_release.outputs.draft }}"
  #         echo "prerelease: ${{ steps.last_release.outputs.prerelease }}"