name: kicker build

on: 
  workflow_call:
    inputs:
      branch_name:
        required: true
        type: string

env:
  CACHE_PREFIX_NODE_MODULES: yarn_1.2
  CACHE_PREFIX_NEXT: next_1.1

jobs:

  build:
    name: Build website
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{inputs.branch_name}}
