name: Slack Notification

on: 
  workflow_call:
    inputs:
      branch_name:
        required: true
        type: string

env:
  CACHE_PREFIX_NODE_MODULES: yarn_1.2
  CACHE_PREFIX_NEXT: next_1.1

jobs:
  send-release-notes:
    name: Send Slack message
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      CI: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{inputs.branch_name}}

      - uses: actions/checkout@v2
      - name: Send Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
