name: Main Trigger

on: [push]

env:
  CACHE_PREFIX_NODE_MODULES: yarn_1.2
  CACHE_PREFIX_NEXT: next_1.1

jobs:
  build_job:
    uses: mikero8/kicker/.github/workflows/build.yml@main
    with:
      branch_name: main

  prepase_releaes_job:
    needs: build_job
    uses: mikero8/kicker/.github/workflows/prepare-release.yml@main
    with:
      branch_name: main

  # notify_slack:
  #   needs: prepase_releaes_job
  #   runs-on: ubuntu-latest
  #   environment: staging
  #   steps:
  #     - uses: ./.github/workflows/slack-notification.yaml
  #       with:
  #         username: ${{ inputs.username }}
  #         token: ${{ secrets.envPAT }}          
  #         branch_name: main