name: Main Trigger

on: [push]

env:
  CACHE_PREFIX_NODE_MODULES: yarn_1.2
  CACHE_PREFIX_NEXT: next_1.1

jobs:
  reusable_workflow_job:
    uses: mikero8/kicker/.github/workflows/build.yml@main
    with:
      branch_name: main
