name: Main Trigger

on: [push]

env:
  CACHE_PREFIX_NODE_MODULES: yarn_1.2
  CACHE_PREFIX_NEXT: next_1.1

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    uses: mikero8/kicker/.github/workflows/build.yml@master
    with:
      username: ${{ inputs.username }}
      token: ${{ secrets.envPAT }}
